channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=3.6
  - r-tidyverse
  - r-rcpp
  - bioconductor-biocinstaller
  - bioconductor-enhancedvolcano
  - bioconductor-deseq2
  - libgcc 
  - gnutls 
  - libuuid 
  - pandoc 
  - qt 
  - scipy 
  - rclone 
  - genozip
  - ncurses 
  - readline 
  - git 
  - libgfortran 
  - pigz 
  - biopython
  - blast 
  - entrez-direct 
  - emboss 
  - fastqc 
  - multiqc 
  - parallel 
  - gawk
  - bioawk 
  - hmmer 
  - pfam_scan 
  - clustalw 
  - mustang 
  - fastqe 
  - ncbi-datasets-cli 
  - jq 
  - unzip
  - etetoolkit::ete3 
  - etetoolkit::ete3_external_apps
