channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=3.6
  - r-tidyverse
  - r-rcpp
  - bioconductor-biocinstaller
  - bioconductor-enhancedvolcano
  - bioconductor-deseq2
  - mamba
  - libgcc 
  - gnutls 
  - libuuid 
  - pandoc 
  - qt 
  - scipy 
  - rclone 
  - genozip
  - ncurses 
  - readline 
  - git 
  - libgfortran 
  - pigz 
  - parallel 
  - gawk
  - unzip
