#!/bin/bash
set -euxo pipefail

CONDA_DIR="/srv/conda/envs/notebook/"

# fix all perl executables to use the correct perl version
find $CONDA_DIR -name "*.pl" | parallel -q sed -i.bak 's|!/usr/bin/perl|!/usr/bin/env perl|' {}
# install additional tools (probcons, bioinformatics-hacks)
mkdir -p ~/etc/tools && cd ~/etc/tools
# wget http://probcons.stanford.edu/probcons_v1_12.tar.gz && tar xzf probcons_v1_12.tar.gz && cd probcons
# fix compiler headers, see https://stackoverflow.com/questions/9403975/strcmp-was-not-declared-in-this-scope
# parallel -q sed -i.bak 's/#include <string>/#include <string.h>/' ::: *.cc  
# make
# find `pwd` -type f -executable | parallel  ln -s {} $CONDA_DIR/bin/ # link to conda binaries folder
git clone https://github.com/audy/bioinformatics-hacks.git && cd bioinformatics-hacks/bin
find `pwd` -type f -executable | parallel  ln -s {} $CONDA_DIR/bin/ # link to conda binaries folder
# install ncbi databases
printf '; Start the section for BLAST configuration\n[BLAST]\n; Specifies the path where BLAST databases are installed\nBLASTDB=~/etc/databases\n' > $HOME/.ncbirc
mkdir -p ~/etc/databases && cd ~/etc/databases
update_blastdb.pl --source GCS taxdb swissprot 16S_ribosomal_RNA
# install additional tools
cd ~/etc/tools
# Download bench.tar.gz to this folder
wget https://www.drive5.com/bench/bench.tar.gz
tar xzvf bench.tar.gz && cd bench1.0
mkdir qscore_src && cd qscore_src
# Download qscore_src.tar.gz to this folder
wget https://www.drive5.com/qscore/qscore_src.tar.gz && tar xzvf qscore_src.tar.gz
# Fix qscore.h file, see https://www.biostars.org/p/288471/
sed -i.bak 's/#include <errno.h>/#include <errno.h>\n#include <climits>/' qscore.h
make && cp qscore ../
ln -s ~/etc/tools/bench1.0/qscore $CONDA_DIR/bin/ # link to conda binaries folder
